### ISSUE TITLE
T02: Elegir profesionales para formar un tribunal

### ISSUE THREAD

**Issue by m16u3l** [m16u3l/asignacionDeTribulanes#20]
## Descripción
Como administrador, quiero poder conformar el tribunal para un perfil.

## Pre condiciones
Seleccionar un perfil de la lista de perfiles sin asignación de tribunales

## Criterios de aceptación:
- [x] Existe la opción para aumentar y/o reducir el número máximo de profesionales seleccionados para la conformación de un tribunal.
- [x] El número mínimo de profesionales seleccionados para la conformación de un tribunal es tres.
- [x] En caso no se seleccione el número de profesionales designados sistema mostrará un mensaje indicando que faltan seleccionar profesionales.
- [x] Los profesionales seleccionados pueden ser des-seleccionados en cualquier momento mientras no se dé la confirmación para pasar a la siguiente fase.
- [x] Al hacer presionar en un profesional de la sección 'seleccionar profesionales' este pasa a la sección 'profesionales seleccionados'.
- [x] Al hacer presionar en un profesional de la sección 'profesionales seleccionados', este pasa a la sección 'seleccionar profesionales'.

**Comment by leticiablancococa** [comment]
Al hacer presionar en un profesional de la sección 'seleccionar profesionales' este pasa a la sección 'profesionales seleccionados'.
Deberia ser: Si presiona sobre un profesional de la sección 'seleccionar profesionales' este pasa a la sección 'profesionales seleccionados'.

  Al hacer presionar en un profesional de la sección 'profesionales seleccionados', este pasa a la sección 'seleccionar profesionales'.

Deberia ser: Si presiona sobre un profesional de la sección 'profesionales seleccionados', este pasa a la sección 'seleccionar profesionales'.
