### ISSUE TITLE
S07:Buscador de profesionales.

### ISSUE THREAD

**Issue by Unzferk** [m16u3l/asignacionDeTribulanes#31]
## Descripción
Como administrador, quiero tener una barra de búsqueda que busque profesionales en vistas donde haya lista de profesionales.

## Criterios de aceptación
- [x] Se muestra una Barra de Búsqueda en la parte superior a la lista de profesionales.
- [x] Permite buscar por Nombre de Profesional.
- [x] La Barra de Búsquedas es no sensible a Mayúsculas y minúsculas.
- [x] En caso de que el sistema no encontrase posibles resultados en mi búsqueda, muestra un mensaje diciendo "No se encontraron coincidencias"

**Comment by m16u3l** [comment]
no busca por area
es no sensible
