### ISSUE TITLE
S08: Ordenar lista de profesionales.

### ISSUE THREAD

**Issue by Unzferk** [m16u3l/asignacionDeTribulanes#35]
## Descripción
Como administrador quiero ordenar la lista de perfiles de forma alfabética.
## Criterios de Aceptación
- [x] El sistema ordena alfabeticamente (de a-z, A-Z )la lista de perfiles por título de perfil.

**Comment by leticiablancococa** [comment]
En apariencia no estaria ordenado,la razon es que los datos originales tiene espacios o caracteres especiales al inicio no visibles...

Se sugiere a tiempo de migracion de datos eliminar estos espacios excedentes del titulo
