### ISSUE TITLE
P05:Dar por finalizada la defensa de un perfil.

### ISSUE THREAD

**Issue by Unzferk** [m16u3l/asignacionDeTribulanes#38]
## Descripción
Como administrador, quiero dar por finalizado, concluido la defensa de un perfil.

## Pre condiciones
Perfiles con tribunales asignados

## Criterios de aceptación
- [x] Los profesionales asignados al perfil reducen su carga de trabajo.
- [x] Antes de registrar como finalizado, el sistema muestra un ultimo mensaje de confirmación "¿Esta seguro que desea finalizar este perfil?".
- [x] Los perfiles finalizados pasan a la lista de perfiles finalizados.
- [x] Se registra la fecha de finalizacion de un perfil.
## Validados
-Existe la opción de marcar un perfil como finalizado en la lista de perfiles con asignación de tribunal.

**Comment by leticiablancococa** [comment]
Hablando de precondiciones, en este caso serian:

- usuario este autentificado
- perfil a registrar defensa, elegido del conjunto de perfiles con tribunal asignado
